matrix:
    include:
        - language: java
          jdk: oraclejdk8
          before_install:
            - cd code/backend
            - mvn compile -DskipTests=true -U
          install: mvn test
