matrix:
    include:
        - language: java
          jdk: oraclejdk8
          before_install:
            - cd code/backend
            - mvn compile -DskipTests=true -U
          install: mvn test
    include:
        - language: node_js
          sudo: true
          node_js:
            - "4.1"
            - "4.0"
            - "0.12"
            - "0.11"
            - "0.10"
          before_install:
            - cd code/frontend
          install: npm install
          script: npm test
