export const SWITCH_TAB = 'SWITCH_TAB';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const ADD_CONTRACTOR = 'ADD_CONTRACTOR';
export const ADD_CONTRACTOR_FAILED = 'ADD_CONTRACTOR_FAILED';
export const EDIT_CONTRACTOR = 'EDIT_CONTRACTOR';
export const EDIT_CONTRACTOR_FAILED = 'EDIT_CONTRACTOR_FAILED';
export const VIEW_CONTRACTORS = 'VIEW_CONTRACTORS';
export const VIEW_CONTRACTORS_FAILED = 'VIEW_CONTRACTORS_FAILED';

export const ADD_NEW_ROW = 'ADD_NEW_ROW';
export const ADD_NEW_ROW_FAILED = 'ADD_NEW_ROW_FAILED';

export const VIEW_TABLES = 'VIEW_TABLES';
export const VIEW_TABLES_FAILED = 'VIEW_TABLES_FAILED';

export const EDIT_ROW = 'EDIT_ROW';
export const EDIT_ROW_FAILED = 'EDIT_ROW_FAILED';
